[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.1", features = ["rustls"] }
actix-cors = "0.6.0"
tokio = "1.17.0"
actix-rt = "2.6.0"
env_logger = "0.9.0"
log = "0.4.14"
sqlx = { version = "0.6", features = [ "runtime-actix-rustls" , "postgres", "chrono", "uuid", "bigdecimal", "json"] }
futures = "0.3.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0.61", features = ["preserve_order"] }
dotenv = "0.15.0"
serenity = { version = "0.11.2", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "http", "cache"] }
libavacado = { path = "../libavacado" }
moka = { version = "0.8", features = ["future"] }
